current_version = "0.1.3"

[[files]]
path = "pyproject.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "src/atsphinx/sqlite3fts/__init__.py"
search = "__version__ = \"{{current_version}}\""
replace = "__version__ = \"{{new_version}}\""
