name: Run CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
      - name: Lint by pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        id: 'setup-python'
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Setup environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --python='${{ steps.setup-python.outputs.python-path }}'
      - name: Run tests
        run: |
          uv run pytest
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
      - name: Build
        run: |
          pip install flit
          flit build
          ls -l dist
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.10'
      - name: Setup environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
          uv run make -C docs html
